
import React from 'react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white p-4 md:p-8 flex justify-center items-start pt-20">
      <div className="w-full max-w-4xl bg-gray-900 border border-gray-800 p-8 shadow-2xl rounded-xl">
        <h1 className="text-3xl font-bold mb-2 text-cyan-400">Terms of Service</h1>
        <p className="text-gray-500 mb-6">Last Updated: December 30, 2025</p>

        <div className="h-[65vh] overflow-y-auto pr-4 custom-scrollbar">
          <div className="space-y-6 text-gray-300">
            <section>
              <h2 className="text-xl font-semibold text-white mb-2">1. Acceptance of Terms</h2>
              <p>By accessing and using DecisionLens AI (&quot;the Platform&quot;), you agree to be bound by these Terms of Service. If you are using the Platform on behalf of an organization, you agree to these terms for that organization and promise that you have the authority to bind that organization to these terms.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-2">2. Use of Intelligence</h2>
              <p>The strategic insights, biological simulations, and predictive outcomes generated by DecisionLens AI are for decision-support purposes only. The Platform provides probabalistic models, not guarantees of future events. You retain full responsibility for all decisions made based on these outputs.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-2">3. Data Sovereignty & Security</h2>
              <p>We prioritize the security of your strategic data. In &quot;Native Mode&quot;, all data resides locally on your infrastructure (SQLite/File System). We do not have access to your decision models, user data, or API keys unless explicitly shared via export features.</p>
            </section>
            
             <section>
              <h2 className="text-xl font-semibold text-white mb-2">4. AI Provider Integration</h2>
              <p>The Platform integrates with third-party Large Language Models (LLMs) such as OpenAI and Anthropic. Your use of these features is subject to their respective policies. You are responsible for managing your own API keys and accruing costs associated with their usage.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-2">5. Limitation of Liability</h2>
              <p>To the maximum extent permitted by law, DecisionLens AI shall not be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Platform.</p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
